const data = {
  product: [
    {
      title: "Smart watch black",
      image: "/images/flash-4.png",
      Brand: "Xiaomi",
      category: "Smart watch",
      price: "1,000",
      rating: "4.5",
      numReviews: "10",
      countInStock: "10",
    },
    {
      title: "Smart watch black",
      image: "/images/flash-4.png",
      Brand: "Xiaomi",
      category: "Smart watch",
      price: "1,000",
      rating: "4.5",
      numReviews: "10",
      countInStock: "10",
    },
    {
      title: "Smart watch black",
      image: "/images/flash-4.png",
      Brand: "Xiaomi",
      category: "Smart watch",
      price: "1,000",
      rating: "4.5",
      numReviews: "10",
      countInStock: "10",
    },
    {
      title: "Smart watch black",
      image: "/images/flash-4.png",
      Brand: "Xiaomi",
      category: "Smart watch",
      price: "1,000",
      rating: "4.5",
      numReviews: "10",
      countInStock: "10",
    },
    {
      title: "Smart watch black",
      image: "/images/flash-4.png",
      Brand: "Xiaomi",
      category: "Smart watch",
      price: "1,000",
      rating: "4.5",
      numReviews: "10",
      countInStock: "10",
    },
    {
      title: "Smart watch black",
      image: "/images/flash-4.png",
      Brand: "Xiaomi",
      category: "Smart watch",
      price: "1,000",
      rating: "4.5",
      numReviews: "10",
      countInStock: "10",
    },
  ],
};

export default data;
