const data = {
  product: [
    {
      title: "Smart watch black",
      image: "/images/flash-4.png",
      brand: "Xiaomi",
      category: "Smart watch",
      price: 1000,
      rating: 4.5,
      numReviews: 10,
      descriptions: "Smart watch black",
      countInStock: 10,
    },
    {
      title: "Smart watch black",
      image: "/images/flash-4.png",
      brand: "Xiaomi",
      category: "Smart watch",
      price: 1000,
      rating: 4.5,
      numReviews: 10,
      descriptions: "Smart watch black",
      countInStock: 10,
    },
    {
      title: "Smart watch black",
      image: "/images/flash-4.png",
      brand: "Xiaomi",
      category: "Smart watch",
      price: 1000,
      rating: 4.5,
      numReviews: 10,
      descriptions: "Smart watch black",
      countInStock: 10,
    },
    {
      title: "Smart watch black",
      image: "/images/flash-4.png",
      brand: "Xiaomi",
      category: "Smart watch",
      price: 1000,
      rating: 4.5,
      numReviews: 10,
      descriptions: "Smart watch black",
      countInStock: 10,
    },
    {
      title: "Smart watch black",
      image: "/images/flash-4.png",
      brand: "Xiaomi",
      category: "Smart watch",
      price: 1000,
      rating: 4.5,
      numReviews: 10,
      descriptions: "Smart watch black",
      countInStock: 10,
    },
    {
      title: "Smarts watch black",
      image: "/images/flash-4.png",
      brand: "Xiaomi",
      category: "Smart watch",
      price: 1000,
      rating: 4.5,
      numReviews: 10,
      descriptions: "Smart watch black",
      countInStock: 10,
    },
  ],
};

export default data;
