const data = {
  products: [
    {
      name: "Smart watch black",
      image: "/images/flash-1.png",
      brand: "Xiaomi",
      category: "Smart watch",
      price: 1000,
      rating: 4.5,
      numReviews: 10,
      descriptions: "Smart watch black",
      countInStock: 10,
    },
    {
      name: "Smart watch black",
      image: "/images/flash-2.png",
      brand: "Xiaomi",
      category: "Smart watch",
      price: 1000,
      rating: 4.5,
      numReviews: 10,
      descriptions: "Smart watch black",
      countInStock: 10,
    },
    {
      name: "Smart watch black",
      image: "/images/flash-3.png",
      brand: "Xiaomi",
      category: "Smart watch",
      price: 1000,
      rating: 4.5,
      numReviews: 10,
      descriptions: "Smart watch black",
      countInStock: 10,
    },
    {
      name: "Smart watch black",
      image: "/images/flash-4.png",
      brand: "Xiaomi",
      category: "Smart watch",
      price: 1000,
      rating: 4.5,
      numReviews: 10,
      descriptions: "Smart watch black",
      countInStock: 10,
    },
    {
      name: "Smart watch black",
      image: "/images/flash-1.png",
      brand: "Xiaomi",
      category: "Smart watch",
      price: 1000,
      rating: 4.5,
      numReviews: 10,
      descriptions: "Smart watch black",
      countInStock: 10,
    },
    {
      name: "Smart watch black",
      image: "/images/flash-2.png",
      brand: "Xiaomi",
      category: "Smart watch",
      price: 1000,
      rating: 4.5,
      numReviews: 10,
      descriptions: "Smart watch black",
      countInStock: 10,
    },
    {
      name: "Smart watch black",
      image: "/images/flash-3.png",
      brand: "Xiaomi",
      category: "Smart watch",
      price: 1000,
      rating: 4.5,
      numReviews: 10,
      descriptions: "Smart watch black",
      countInStock: 10,
    },
    {
      name: "Smart watch black",
      image: "/images/flash-4.png",
      brand: "Xiaomi",
      category: "Smart watch",
      price: 1000,
      rating: 4.5,
      numReviews: 10,
      descriptions: "Smart watch black",
      countInStock: 10,
    },
  ],
};

export default data;
